# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'build_product_windows'

      pool:
          vmImage: 'windows-latest'

      steps:
          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-interactive.yaml
          - template: electron-e2e-publish-results.yaml
          - template: electron-update-config.yaml

          - template: distribute-electron.yaml

    - job: 'build_product_linux'

      pool:
          vmImage: 'ubuntu-16.04'

      steps:
          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-linux.yaml
          - template: electron-e2e-publish-results.yaml
          - template: electron-update-config.yaml

          - template: distribute-electron.yaml

    - job: 'build_product_mac'
      pool:
          vmImage: macOS-10.14
      steps:
          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-interactive.yaml
          - template: electron-e2e-publish-results.yaml
          - template: electron-update-config.yaml

          - template: distribute-electron.yaml
